model = "gpt-5.4"
model_reasoning_effort = "xhigh"
service_tier = "fast"

[profiles.fast]
model = "gpt-5.4"
model_reasoning_effort = "xhigh"

[projects."/Users/aagrigore1"]
trust_level = "trusted"

[projects."/Users/aagrigore1/src/mts/mymts/app"]
trust_level = "trusted"

[projects."/Users/aagrigore1/Downloads"]
trust_level = "trusted"

[projects."/Users/aagrigore1/src/mts/membrana/ios/packages/darwin-httpclient"]
trust_level = "trusted"

[projects."/Users/aagrigore1/src/mts/bsim"]
trust_level = "trusted"

[projects."/Users/aagrigore1/src/mts/membrana/ios/ios-membrana-app-redesign"]
trust_level = "trusted"

[projects."/Users/aagrigore1/src/deps_duplicate_sample"]
trust_level = "trusted"

[projects."/Users/aagrigore1/.claude/skills"]
trust_level = "untrusted"

[projects."/Users/alexis/src/xflow/xcflow-ios_comparison"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[projects."/Users/alexis/src/xflow/xflow-ios"]
trust_level = "trusted"

[projects."/Users/alexis/src/relux-works/skill-project-management"]
trust_level = "trusted"

[projects."/Users/alexis/src/relux-works/skill-ios-app-manager"]
trust_level = "trusted"

[projects."/Users/alexis"]
trust_level = "trusted"

[projects."/Users/alexis/src/patents/mcp-with-approvals"]
trust_level = "trusted"

[projects."/Users/alexis/src/relux-works/skill-market-impulse"]
trust_level = "trusted"

[projects."/Users/alexis/src/relux-works/skill-currency-exchange"]
trust_level = "trusted"

[projects."/Users/alexis/src/bsim"]
trust_level = "trusted"

[projects."/Users/alexis/src/multi-tun"]
trust_level = "trusted"

[projects."/Users/alexis/src/interview_questions"]
trust_level = "trusted"

[projects."/Users/alexis/Downloads"]
trust_level = "trusted"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.4" = "gpt-5.4-codex"
